name: Update Playlist
on:
  schedule:
    - cron: '0 0 * * *' # อัปเดตทุกเที่ยงคืน
  workflow_dispatch: # กดอัปเดตเองได้

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Content
        run: |
          echo "#EXTM3U" > playlist.m3u
          echo "#EXTINF:-1 tvg-logo=\"https://www.amarintv.com/assets/images/logo.png\", Amarin TV" >> playlist.m3u
          echo "https://amarin-ks7jcc.cdn.byteark.com/live/Thai_HD_index.m3u8?x_ark_access_id=fleet-868&x_ark_auth_type=ark-v2&x_ark_expires=1770812209&x_ark_path_prefix=%2Flive%2F&x_ark_signature=Il8BaYxu9H6wmm3LC3XFHw" >> playlist.m3u
          echo "#EXTINF:-1 tvg-logo=\"https://www.amarintv.com/assets/images/logo.png\", Amarin TV" >> playlist.m3u
          echo "https://amarin-ks7jcc.cdn.byteark.com/live/Thai_HD_index.m3u8?x_ark_access_id=fleet-868&x_ark_auth_type=ark-v2&x_ark_expires=1770812209&x_ark_path_prefix=%2Flive%2F&x_ark_signature=Il8BaYxu9H6wmm3LC3XFHw" >> playlist.m3u
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist" || exit 0
          git push
